# Header
menu:
  Home: /
  Archives: /archives/
  Links: /links/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# Code Highlight theme
# Available value:
#    normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: normal

links:
  - url: https://qvq.im/
    name: 4uuu Nya
    img: https://qvq.im/static/img/avatar.png
    info: 4uuu Nya's Blog
  - url: http://www.wiattack.net/
    name: icecolor
    img:
    info: icecolor's Blog
  - url: http://n3k0sec.top/
    name: n3k0
    img: https://i.loli.net/2018/12/11/5c0f283aaf798.jpg
    info: n3k0's Blog